# This file intentionally left blank

MCU = RP2040
BOOTLOADER = rp2040

VIA_ENABLE = yes
MOUSEKEY_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER_ENABLE = yes
OLED_DRIVER = ssd1306
LTO_ENABLE = yes

AUDIO_ENABLE = yes
AUDIO_DRIVER = pwm_hardware

ENCODER_ENABLE = yes

WPM_ENABLE = yes

OPT_DEFS += -DHAL_USE_I2C=TRUE